#!/usr/bin/env node
// serve-static.mjs — a dev static server that can actually serve the worker.
//
// WHY THIS EXISTS. `src/web.glyph` hard-codes four routes (`/`, `/xox.css`,
// `/xox.js`, `/api/move`) and answers 404 for everything else, so it cannot
// serve `/worker.js` or the `/engine/**` tree. specs/architecture.md §2.5
// already flags that as a change the Shell owner has to make. Until it lands,
// this is what serves `assets/` for a browser check — and it is also the more
// honest test surface, because production (D-2, G-4) is a plain static host
// with no Glyph in it at all.
//
//   node tools/serve-static.mjs --port 8080
//   node tools/serve-static.mjs --port 8080 --probe   # + tools/probe/**
//
// `--probe` additionally serves tools/probe/ from the same origin, so a
// harness page can `new Worker("/worker.js", {type:"module"})` without putting
// a file into assets/, which this agent does not own.
//
// No npm dependencies. Dev only: it never leaves localhost and it is not part
// of the shipped app.

import { createServer } from "node:http";
import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, extname, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".map": "application/json; charset=utf-8",
};

const argv = process.argv.slice(2);
let port = 8080;
let probe = false;
let quiet = false;
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--port") port = Number(argv[++i]);
  else if (argv[i] === "--probe") probe = true;
  else if (argv[i] === "--quiet") quiet = true;
}

const roots = [join(ROOT, "assets")];
if (probe) roots.push(join(ROOT, "tools", "probe"));

// Resolve a URL path to a file inside one of the roots, or null. `normalize`
// collapses `..` before the prefix check, so a traversal cannot escape.
function locate(urlPath) {
  const clean = normalize(decodeURIComponent(urlPath.split("?")[0]));
  const rel = clean === "/" ? "index.html" : clean.replace(/^\/+/, "");
  for (const root of roots) {
    const file = resolve(root, rel);
    if (!file.startsWith(root)) continue;
    if (existsSync(file) && statSync(file).isFile()) return file;
  }
  return null;
}

// --- the load-event latch (probe mode only) --------------------------------
//
// `chrome --headless=new --dump-dom` prints the DOM at the load event, and
// `--virtual-time-budget` is no help here: virtual time fast-forwards while
// the main thread sits idle awaiting the worker, so the budget expires within
// milliseconds of real time and the page is cut off two checks in (observed).
//
// So the probe page ends with `<script defer src="/__hold.js">`. A deferred
// script delays the load event until it has been fetched, and this server
// simply does not answer that request until the page POSTs `/__done`. The
// dump then lands after the last assertion, deterministically, with no
// sleeping and no guessing at how long a search takes.
const held = [];
const HOLD_CEILING_MS = 120000;

function release(why) {
  while (held.length > 0) {
    const res = held.pop();
    res.writeHead(200, { "content-type": TYPES[".js"], "cache-control": "no-store" });
    res.end(`// ${why}\n`);
  }
}

const server = createServer((req, res) => {
  if (probe && req.url === "/__hold.js") {
    held.push(res);
    setTimeout(() => release("released on timeout"), HOLD_CEILING_MS).unref?.();
    return;
  }
  if (probe && req.url === "/__done") {
    let body = "";
    req.on("data", (chunk) => { body += chunk; });
    req.on("end", () => {
      res.writeHead(204).end();
      if (!quiet) console.log(`  probe reported:\n${body.replace(/^/gm, "    ")}`);
      release("probe complete");
    });
    return;
  }

  const file = locate(req.url ?? "/");
  if (file === null) {
    if (!quiet) console.log(`  404 ${req.url}`);
    res.writeHead(404, { "content-type": "text/plain; charset=utf-8" });
    res.end("not found");
    return;
  }
  const type = TYPES[extname(file)] ?? "application/octet-stream";
  const body = readFileSync(file);
  if (!quiet) console.log(`  200 ${req.url}  (${type.split(";")[0]}, ${body.length} B)`);
  res.writeHead(200, {
    "content-type": type,
    "content-length": body.length,
    // The engine bundle is regenerated by every build; never let a browser
    // hand back a stale module during a check.
    "cache-control": "no-store",
  });
  res.end(body);
});

server.listen(port, "127.0.0.1", () => {
  console.log(`serve-static: http://127.0.0.1:${port}  roots: ${roots.map((r) => r.replace(`${ROOT}/`, "")).join(", ")}`);
});
